spring:
  jta:
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    mapping-resources:
      - META-INF/employee.orm.hbm.xml
